packages:
  - packages/*
  - apps/*

catalog:
  '@iconify-json/mingcute': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.47
  '@tailwindcss/vite': 4.1.12
  '@types/markdown-it': ^14.1.2
  '@types/node': ^24.2.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.7.0
  dompurify: ^3.2.6
  markdown-it: ^14.1.0
  markdown-it-abbr: ^2.0.0
  markdown-it-anchor: ^9.2.0
  markdown-it-container: ^4.0.0
  markdown-it-deflist: ^3.0.0
  markdown-it-emoji: ^3.0.0
  markdown-it-footnote: 4.0.0
  markdown-it-ins: ^4.0.0
  markdown-it-mark: ^4.0.0
  markdown-it-sub: ^2.0.0
  markdown-it-sup: ^2.0.0
  tailwindcss: 4.1.12
  typescript: ~5.8.3
  unplugin-icons: ^22.2.0
  vite: ^7.1.0
  vue: 3.5.18
  vue-tsc: ^3.0.5
